language: java
jdk:
  - openjdk8

before_script:
  - mkdir -p bin
  - export PATH=$PATH:$PWD/bin
  - wget https://github.com/owlcollab/owltools/releases/download/2020-04-06/owltools -O bin/owltools
  - wget https://github.com/owlcollab/owltools/releases/download/2020-04-06/ontology-release-runner -O bin/ontology-release-runner
#  - wget http://build.berkeleybop.org/userContent/owltools/owltools-runner-all.jar -O bin/owltools-runner-all.jar
  - wget https://github.com/owlcollab/owltools/releases/download/2020-04-06/owltools-oort-all.jar -O bin/owltools-oort-all.jar
  - wget https://raw.githubusercontent.com/geneontology/go-ontology/master/src/util/check-obo-for-standard-release.pl -O bin/check-obo-for-standard-release.pl
  - wget https://raw.githubusercontent.com/ontodev/robot/master/bin/robot -O bin/robot
  - wget https://github.com/ontodev/robot/releases/download/v1.8.1/robot.jar -O bin/robot.jar
  - chmod +x bin/*

# command to run tests
script: make test

#after_success:
#  coveralls

# whitelist
branches:
  only:
    - master

notifications:
  email:
    - cjmungall@lbl.gov

